#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.
#+require "fileutils"
#+FileUtils.mkdir_p 'tmp'
#+FileUtils.mkdir_p 'tmp/cache'
#+FileUtils.mkdir_p 'tmp/pids'
#+FileUtils.mkdir_p 'tmp/sessions'
#+FileUtils.mkdir_p 'tmp/sockets'
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'
